// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
/**
 * URL of a catalog service icon generated by pnpm icons:fetch (public/icons/<serviceId>.svg,
 * not committed: ADR-0012). If it is missing, ServiceIcon shows its fallback.
 */
export const serviceIconSrc = (serviceId: string): string =>
  `${import.meta.env.BASE_URL}icons/${serviceId}.svg`;
